export const SEND_TEXT = 'SEND_TEXT';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const SET_PEOPLE_LIST_DATA = 'SET_PEOPLE_LIST_DATA';
export const SET_CREATE_PERSON_REQUEST_STATUS = 'SET_CREATE_PERSON_REQUEST_STATUS';